stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:
  stage: build
  tags : 
    - python
  script:
    - echo "Installing dependencies..."
    - pip install -r requirements.txt

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  tags : 
    - python
  script:
    - echo "Running unit tests..."
    - pytest tests/  # Run all tests in the tests/ directory.
    