# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddingBoardUI(object):
    def setupUi(self, AddingBoardUI):
        AddingBoardUI.setObjectName("AddingBoardUI")
        AddingBoardUI.resize(400, 300)
        AddingBoardUI.setStyleSheet("")
        self.AddingBoard = QtWidgets.QWidget(AddingBoardUI)
        self.AddingBoard.setGeometry(QtCore.QRect(80, 100, 161, 131))
        self.AddingBoard.setStyleSheet("#AddingBoard{\n"
"    border: 2px solid #052659;\n"
"    background-color: #D0E3FF;\n"
"    border-radius: 17px;\n"
"}")
        self.AddingBoard.setObjectName("AddingBoard")
        self.BoardTitle = QtWidgets.QLabel(self.AddingBoard)
        self.BoardTitle.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.BoardTitle.setStyleSheet("#BoardTitle{\n"
"    font-family: Rubik;\n"
"    font-size: 11px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.BoardTitle.setObjectName("BoardTitle")
        self.inputBoardtitle = QtWidgets.QLineEdit(self.AddingBoard)
        self.inputBoardtitle.setGeometry(QtCore.QRect(10, 30, 141, 22))
        self.inputBoardtitle.setStyleSheet("#inputBoardtitle{\n"
"    border-radius : 10px;\n"
"}")
        self.inputBoardtitle.setObjectName("inputBoardtitle")
        self.BoardTitle_2 = QtWidgets.QLabel(self.AddingBoard)
        self.BoardTitle_2.setGeometry(QtCore.QRect(10, 60, 131, 16))
        self.BoardTitle_2.setStyleSheet("#BoardTitle_2{\n"
"    font-family: Rubik;\n"
"    font-size: 11px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.BoardTitle_2.setObjectName("BoardTitle_2")
        self.CreateBoard = QtWidgets.QPushButton(self.AddingBoard)
        self.CreateBoard.setGeometry(QtCore.QRect(10, 100, 141, 24))
        self.CreateBoard.setStyleSheet("#CreateBoard{\n"
"    font-family: Rubik;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.CreateBoard.setObjectName("CreateBoard")

        self.retranslateUi(AddingBoardUI)
        QtCore.QMetaObject.connectSlotsByName(AddingBoardUI)

    def retranslateUi(self, AddingBoardUI):
        _translate = QtCore.QCoreApplication.translate
        AddingBoardUI.setWindowTitle(_translate("AddingBoardUI", "Dialog"))
        self.BoardTitle.setText(_translate("AddingBoardUI", "Board Title"))
        self.BoardTitle_2.setText(_translate("AddingBoardUI", "Board Title is required"))
        self.CreateBoard.setText(_translate("AddingBoardUI", "Create"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddingBoardUI = QtWidgets.QDialog()
    ui = Ui_AddingBoardUI()
    ui.setupUi(AddingBoardUI)
    AddingBoardUI.show()
    sys.exit(app.exec_())
