# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addproject.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddingProjectUI(object):
    def setupUi(self, AddingProjectUI):
        AddingProjectUI.setObjectName("AddingProjectUI")
        AddingProjectUI.resize(400, 300)
        self.AddingProject = QtWidgets.QWidget(AddingProjectUI)
        self.AddingProject.setGeometry(QtCore.QRect(80, 100, 161, 131))
        self.AddingProject.setStyleSheet("#Sorting{\n"
"    border: 2px solid #052659;\n"
"    background-color: #D0E3FF;\n"
"    border-radius: 17px;\n"
"}")
        self.AddingProject.setObjectName("AddingProject")
        self.ProjectTitle = QtWidgets.QLabel(self.AddingProject)
        self.ProjectTitle.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.ProjectTitle.setStyleSheet("#ProjectTitle{\n"
"    font-family: Rubik;\n"
"    font-size: 11px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.ProjectTitle.setObjectName("ProjectTitle")
        self.inputPtitle = QtWidgets.QLineEdit(self.AddingProject)
        self.inputPtitle.setGeometry(QtCore.QRect(10, 30, 141, 22))
        self.inputPtitle.setStyleSheet("#inputPtitle{\n"
"    border-radius : 10px;\n"
"}")
        self.inputPtitle.setObjectName("inputPtitle")
        self.ProjectTitle_2 = QtWidgets.QLabel(self.AddingProject)
        self.ProjectTitle_2.setGeometry(QtCore.QRect(10, 60, 131, 16))
        self.ProjectTitle_2.setStyleSheet("#ProjectTitle_2{\n"
"    font-family: Rubik;\n"
"    font-size: 11px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.ProjectTitle_2.setObjectName("ProjectTitle_2")
        self.create = QtWidgets.QPushButton(self.AddingProject)
        self.create.setGeometry(QtCore.QRect(10, 100, 141, 24))
        self.create.setStyleSheet("#create{\n"
"    font-family: Rubik;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.create.setObjectName("create")

        self.retranslateUi(AddingProjectUI)
        QtCore.QMetaObject.connectSlotsByName(AddingProjectUI)

    def retranslateUi(self, AddingProjectUI):
        _translate = QtCore.QCoreApplication.translate
        AddingProjectUI.setWindowTitle(_translate("AddingProjectUI", "Dialog"))
        self.ProjectTitle.setText(_translate("AddingProjectUI", "Project Title"))
        self.ProjectTitle_2.setText(_translate("AddingProjectUI", "Project Title is required"))
        self.create.setText(_translate("AddingProjectUI", "Create"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddingProjectUI = QtWidgets.QDialog()
    ui = Ui_AddingProjectUI()
    ui.setupUi(AddingProjectUI)
    AddingProjectUI.show()
    sys.exit(app.exec_())
