# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'boardpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ergo(object):
    def setupUi(self, Ergo):
        Ergo.setObjectName("Ergo")
        Ergo.resize(1920, 1080)
        self.Navbar = QtWidgets.QWidget(Ergo)
        self.Navbar.setGeometry(QtCore.QRect(0, 0, 131, 1081))
        self.Navbar.setStyleSheet("#Navbar{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #5483B3, stop:1 #24384D);\n"
"}")
        self.Navbar.setObjectName("Navbar")
        self.LogoErgo = QtWidgets.QLabel(self.Navbar)
        self.LogoErgo.setGeometry(QtCore.QRect(-40, 30, 201, 191))
        self.LogoErgo.setStyleSheet("")
        self.LogoErgo.setText("")
        self.LogoErgo.setPixmap(QtGui.QPixmap("../../img/logoergo.png"))
        self.LogoErgo.setScaledContents(True)
        self.LogoErgo.setObjectName("LogoErgo")
        self.MainSection = QtWidgets.QWidget(Ergo)
        self.MainSection.setGeometry(QtCore.QRect(130, 60, 1811, 1031))
        self.MainSection.setStyleSheet("#MainSection{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #DAD9D8, stop:1 #97C9ED);\n"
"}")
        self.MainSection.setObjectName("MainSection")
        self.BoardName = QtWidgets.QLabel(self.MainSection)
        self.BoardName.setGeometry(QtCore.QRect(20, 20, 561, 71))
        self.BoardName.setStyleSheet("#BoardName{\n"
"    font: 50px \"Roboto\";\n"
"    color: #5483B3;\n"
"    font-weight: bold;\n"
"}")
        self.BoardName.setObjectName("BoardName")
        self.Containerforwords = QtWidgets.QWidget(self.MainSection)
        self.Containerforwords.setGeometry(QtCore.QRect(10, 100, 621, 121))
        self.Containerforwords.setStyleSheet("#Containerforwords{\n"
"    border: 2px solid #9FB0CC;\n"
"    background-color: #ECECF3;\n"
"    border-radius: 17px;\n"
"}")
        self.Containerforwords.setObjectName("Containerforwords")
        self.Welcome = QtWidgets.QLabel(self.Containerforwords)
        self.Welcome.setGeometry(QtCore.QRect(10, 20, 171, 31))
        self.Welcome.setStyleSheet("#Welcome {\n"
"    font: bold 30px \"Roboto\";\n"
"    color: #7DA0CA;\n"
"}")
        self.Welcome.setObjectName("Welcome")
        self.WelcomeProject = QtWidgets.QLabel(self.Containerforwords)
        self.WelcomeProject.setGeometry(QtCore.QRect(10, 70, 591, 31))
        self.WelcomeProject.setStyleSheet("#WelcomeProject {\n"
"    font: bold 18px \"Roboto\";\n"
"    color: #7DA0CA;\n"
"}")
        self.WelcomeProject.setObjectName("WelcomeProject")
        self.YourProject = QtWidgets.QLabel(self.MainSection)
        self.YourProject.setGeometry(QtCore.QRect(20, 240, 341, 91))
        self.YourProject.setStyleSheet("#YourProject{\n"
"    font: 45px \"Roboto\";\n"
"    color: #5483B3;\n"
"    font-weight: bold;\n"
"}")
        self.YourProject.setObjectName("YourProject")
        self.AddProjectButton = QtWidgets.QPushButton(self.MainSection)
        self.AddProjectButton.setGeometry(QtCore.QRect(200, 330, 151, 31))
        self.AddProjectButton.setStyleSheet("#AddProjectButton{\n"
"    border: 2px solid #9FB0CC;\n"
"    background-color: #ECECF3;\n"
"    border-radius: 10px;\n"
"    font-family: \"Roboto\";\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #5483B3;\n"
"}")
        self.AddProjectButton.setObjectName("AddProjectButton")
        self.FavoriteProject = QtWidgets.QLabel(self.MainSection)
        self.FavoriteProject.setGeometry(QtCore.QRect(20, 620, 401, 91))
        self.FavoriteProject.setStyleSheet("#FavoriteProject{\n"
"    font: 45px \"Roboto\";\n"
"    color: #5483B3;\n"
"    font-weight: bold;\n"
"}")
        self.FavoriteProject.setObjectName("FavoriteProject")
        self.QuickAccess = QtWidgets.QLabel(self.MainSection)
        self.QuickAccess.setGeometry(QtCore.QRect(20, 700, 661, 31))
        self.QuickAccess.setStyleSheet("#QuickAccess\n"
"{\n"
"    font: 20px \"Roboto\";\n"
"    color: #5483B3;\n"
"    font-weight: bold;\n"
"}")
        self.QuickAccess.setObjectName("QuickAccess")
        self.ContainerForBoards = QtWidgets.QWidget(self.MainSection)
        self.ContainerForBoards.setGeometry(QtCore.QRect(20, 370, 821, 261))
        self.ContainerForBoards.setStyleSheet("#ContainerForBoards{\n"
"    border-radius : 10px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #5F84A2, stop:1 #91AEC4);\n"
"}")
        self.ContainerForBoards.setObjectName("ContainerForBoards")
        self.Board2 = QtWidgets.QPushButton(self.ContainerForBoards)
        self.Board2.setGeometry(QtCore.QRect(260, 20, 221, 61))
        self.Board2.setStyleSheet("#Board2{\n"
"    background-color: #F6F6F6;\n"
"    border-radius: 10px;\n"
"    font-family: \"Roboto\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"   color: #5483B3;\n"
"}")
        self.Board2.setObjectName("Board2")
        self.Project1 = QtWidgets.QPushButton(self.ContainerForBoards)
        self.Project1.setGeometry(QtCore.QRect(20, 20, 221, 61))
        self.Project1.setStyleSheet("#Project1{\n"
"    background-color: #F6F6F6;\n"
"    border-radius: 10px;\n"
"    font-family: \"Roboto\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"   color: #5483B3;\n"
"}")
        self.Project1.setObjectName("Project1")
        self.Board3 = QtWidgets.QPushButton(self.ContainerForBoards)
        self.Board3.setGeometry(QtCore.QRect(500, 20, 221, 61))
        self.Board3.setStyleSheet("#Board3{\n"
"    background-color: #F6F6F6;\n"
"    border-radius: 10px;\n"
"    font-family: \"Roboto\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"   color: #5483B3;\n"
"}")
        self.Board3.setObjectName("Board3")
        self.Board1_2 = QtWidgets.QPushButton(self.ContainerForBoards)
        self.Board1_2.setGeometry(QtCore.QRect(20, 90, 221, 61))
        self.Board1_2.setStyleSheet("#Board1_2{\n"
"    background-color: #F6F6F6;\n"
"    border-radius: 10px;\n"
"    font-family: \"Roboto\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"   color: #5483B3;\n"
"}")
        self.Board1_2.setObjectName("Board1_2")
        self.Board1_3 = QtWidgets.QPushButton(self.ContainerForBoards)
        self.Board1_3.setGeometry(QtCore.QRect(260, 90, 221, 61))
        self.Board1_3.setStyleSheet("#Board1_3{\n"
"    background-color: #F6F6F6;\n"
"    border-radius: 10px;\n"
"    font-family: \"Roboto\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"   color: #5483B3;\n"
"}")
        self.Board1_3.setObjectName("Board1_3")
        self.Board1_4 = QtWidgets.QPushButton(self.ContainerForBoards)
        self.Board1_4.setGeometry(QtCore.QRect(500, 90, 221, 61))
        self.Board1_4.setStyleSheet("#Board1_4{\n"
"    background-color: #F6F6F6;\n"
"    border-radius: 10px;\n"
"    font-family: \"Roboto\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"   color: #5483B3;\n"
"}")
        self.Board1_4.setObjectName("Board1_4")
        self.Board1_5 = QtWidgets.QPushButton(self.ContainerForBoards)
        self.Board1_5.setGeometry(QtCore.QRect(20, 170, 221, 61))
        self.Board1_5.setStyleSheet("#Board1_5{\n"
"    background-color: #F6F6F6;\n"
"    border-radius: 10px;\n"
"    font-family: \"Roboto\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"   color: #5483B3;\n"
"}")
        self.Board1_5.setObjectName("Board1_5")
        self.Board1_6 = QtWidgets.QPushButton(self.ContainerForBoards)
        self.Board1_6.setGeometry(QtCore.QRect(260, 170, 221, 61))
        self.Board1_6.setStyleSheet("#Board1_6{\n"
"    background-color: #F6F6F6;\n"
"    border-radius: 10px;\n"
"    font-family: \"Roboto\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"   color: #5483B3;\n"
"}")
        self.Board1_6.setObjectName("Board1_6")
        self.Board1_7 = QtWidgets.QPushButton(self.ContainerForBoards)
        self.Board1_7.setGeometry(QtCore.QRect(500, 170, 221, 61))
        self.Board1_7.setStyleSheet("#Board1_7{\n"
"    background-color: #F6F6F6;\n"
"    border-radius: 10px;\n"
"    font-family: \"Roboto\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"   color: #5483B3;\n"
"}")
        self.Board1_7.setObjectName("Board1_7")
        self.Setting = QtWidgets.QPushButton(self.ContainerForBoards)
        self.Setting.setGeometry(QtCore.QRect(200, 20, 41, 31))
        self.Setting.setStyleSheet("#Setting{\n"
"    border : none;\n"
"}")
        self.Setting.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../img/3dot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Setting.setIcon(icon)
        self.Setting.setObjectName("Setting")
        self.Setting_2 = QtWidgets.QPushButton(self.ContainerForBoards)
        self.Setting_2.setGeometry(QtCore.QRect(440, 20, 41, 31))
        self.Setting_2.setStyleSheet("#Setting_2{\n"
"    border : none;\n"
"}")
        self.Setting_2.setText("")
        self.Setting_2.setIcon(icon)
        self.Setting_2.setObjectName("Setting_2")
        self.Setting_3 = QtWidgets.QPushButton(self.ContainerForBoards)
        self.Setting_3.setGeometry(QtCore.QRect(200, 90, 41, 31))
        self.Setting_3.setStyleSheet("#Setting_3{\n"
"    border : none;\n"
"}")
        self.Setting_3.setText("")
        self.Setting_3.setIcon(icon)
        self.Setting_3.setObjectName("Setting_3")
        self.Setting_4 = QtWidgets.QPushButton(self.ContainerForBoards)
        self.Setting_4.setGeometry(QtCore.QRect(440, 90, 41, 31))
        self.Setting_4.setStyleSheet("#Setting_4{\n"
"    border : none;\n"
"}")
        self.Setting_4.setText("")
        self.Setting_4.setIcon(icon)
        self.Setting_4.setObjectName("Setting_4")
        self.Setting_5 = QtWidgets.QPushButton(self.ContainerForBoards)
        self.Setting_5.setGeometry(QtCore.QRect(680, 20, 41, 31))
        self.Setting_5.setStyleSheet("#Setting_5{\n"
"    border : none;\n"
"}")
        self.Setting_5.setText("")
        self.Setting_5.setIcon(icon)
        self.Setting_5.setObjectName("Setting_5")
        self.Setting_6 = QtWidgets.QPushButton(self.ContainerForBoards)
        self.Setting_6.setGeometry(QtCore.QRect(680, 90, 41, 31))
        self.Setting_6.setStyleSheet("#Setting_6{\n"
"    border : none;\n"
"}")
        self.Setting_6.setText("")
        self.Setting_6.setIcon(icon)
        self.Setting_6.setObjectName("Setting_6")
        self.Setting_7 = QtWidgets.QPushButton(self.ContainerForBoards)
        self.Setting_7.setGeometry(QtCore.QRect(200, 170, 41, 31))
        self.Setting_7.setStyleSheet("#Setting_7{\n"
"    border : none;\n"
"}")
        self.Setting_7.setText("")
        self.Setting_7.setIcon(icon)
        self.Setting_7.setObjectName("Setting_7")
        self.Setting_8 = QtWidgets.QPushButton(self.ContainerForBoards)
        self.Setting_8.setGeometry(QtCore.QRect(440, 170, 41, 31))
        self.Setting_8.setStyleSheet("#Setting_8{\n"
"    border : none;\n"
"}")
        self.Setting_8.setText("")
        self.Setting_8.setIcon(icon)
        self.Setting_8.setObjectName("Setting_8")
        self.Setting_9 = QtWidgets.QPushButton(self.ContainerForBoards)
        self.Setting_9.setGeometry(QtCore.QRect(680, 170, 41, 31))
        self.Setting_9.setStyleSheet("#Setting_9\n"
"{\n"
"    border : none;\n"
"}")
        self.Setting_9.setText("")
        self.Setting_9.setIcon(icon)
        self.Setting_9.setObjectName("Setting_9")
        self.ContainerForBoards_2 = QtWidgets.QWidget(self.MainSection)
        self.ContainerForBoards_2.setGeometry(QtCore.QRect(20, 740, 821, 261))
        self.ContainerForBoards_2.setStyleSheet("#ContainerForBoards_2{\n"
"    border-radius : 10px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #5F84A2, stop:1 #91AEC4);\n"
"}")
        self.ContainerForBoards_2.setObjectName("ContainerForBoards_2")
        self.Favp1 = QtWidgets.QPushButton(self.ContainerForBoards_2)
        self.Favp1.setGeometry(QtCore.QRect(20, 30, 221, 61))
        self.Favp1.setStyleSheet("#Favp1{\n"
"    background-color: #F6F6F6;\n"
"    border-radius: 10px;\n"
"    font-family: \"Roboto\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"   color: #5483B3;\n"
"}")
        self.Favp1.setObjectName("Favp1")
        self.AddingProject = QtWidgets.QWidget(self.MainSection)
        self.AddingProject.setGeometry(QtCore.QRect(360, 320, 271, 211))
        self.AddingProject.setStyleSheet("#AddingProject{\n"
"    border: 2px solid #052659;\n"
"    background-color: #D0E3FF;\n"
"    border-radius: 17px;\n"
"}")
        self.AddingProject.setObjectName("AddingProject")
        self.BoardTitle = QtWidgets.QLabel(self.AddingProject)
        self.BoardTitle.setGeometry(QtCore.QRect(20, 20, 101, 21))
        self.BoardTitle.setStyleSheet("#BoardTitle{\n"
"    font-family: Rubik;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.BoardTitle.setObjectName("BoardTitle")
        self.BoardTitle_2 = QtWidgets.QLabel(self.AddingProject)
        self.BoardTitle_2.setGeometry(QtCore.QRect(20, 90, 181, 21))
        self.BoardTitle_2.setStyleSheet("#BoardTitle_2{\n"
"    font-family: Rubik;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.BoardTitle_2.setObjectName("BoardTitle_2")
        self.inputBoardtitle = QtWidgets.QLineEdit(self.AddingProject)
        self.inputBoardtitle.setGeometry(QtCore.QRect(10, 50, 251, 31))
        self.inputBoardtitle.setStyleSheet("#inputBoardtitle{\n"
"    border-radius : 10px;\n"
"}")
        self.inputBoardtitle.setObjectName("inputBoardtitle")
        self.CreateBoard = QtWidgets.QPushButton(self.AddingProject)
        self.CreateBoard.setGeometry(QtCore.QRect(10, 150, 251, 41))
        self.CreateBoard.setStyleSheet("#CreateBoard{\n"
"    font-family: Rubik;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.CreateBoard.setObjectName("CreateBoard")
        self.Sorting = QtWidgets.QPushButton(self.MainSection)
        self.Sorting.setGeometry(QtCore.QRect(30, 330, 151, 31))
        self.Sorting.setStyleSheet("#Sorting{\n"
"    border: 2px solid #9FB0CC;\n"
"    background-color: #ECECF3;\n"
"    border-radius: 10px;\n"
"    font-family: \"Roboto\";\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #5483B3;\n"
"}")
        self.Sorting.setObjectName("Sorting")
        self.Actions = QtWidgets.QWidget(self.MainSection)
        self.Actions.setGeometry(QtCore.QRect(750, 540, 271, 171))
        self.Actions.setStyleSheet("#Actions{\n"
"    border: 2px solid #052659;\n"
"    background-color: #D0E3FF;\n"
"    border-radius: 17px;\n"
"}")
        self.Actions.setObjectName("Actions")
        self.BoardTitle_3 = QtWidgets.QLabel(self.Actions)
        self.BoardTitle_3.setGeometry(QtCore.QRect(20, 20, 101, 21))
        self.BoardTitle_3.setStyleSheet("#BoardTitle_3{\n"
"    font-family: Rubik;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.BoardTitle_3.setObjectName("BoardTitle_3")
        self.Favorite = QtWidgets.QPushButton(self.Actions)
        self.Favorite.setGeometry(QtCore.QRect(10, 50, 251, 41))
        self.Favorite.setStyleSheet("#Favorite{\n"
"    font-family: Rubik;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../img/star.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Favorite.setIcon(icon1)
        self.Favorite.setObjectName("Favorite")
        self.DeleteProject = QtWidgets.QPushButton(self.Actions)
        self.DeleteProject.setGeometry(QtCore.QRect(10, 100, 251, 41))
        self.DeleteProject.setStyleSheet("#DeleteProject{\n"
"    font-family: Rubik;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../img/trashcan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DeleteProject.setIcon(icon2)
        self.DeleteProject.setObjectName("DeleteProject")
        self.SortingOption = QtWidgets.QWidget(self.MainSection)
        self.SortingOption.setGeometry(QtCore.QRect(30, 370, 271, 121))
        self.SortingOption.setStyleSheet("#SortingOption\n"
"{\n"
"    border: 2px solid #052659;\n"
"    background-color: #D0E3FF;\n"
"    border-radius: 17px;\n"
"}")
        self.SortingOption.setObjectName("SortingOption")
        self.Sort1 = QtWidgets.QPushButton(self.SortingOption)
        self.Sort1.setGeometry(QtCore.QRect(10, 60, 251, 41))
        self.Sort1.setStyleSheet("#Sort1{\n"
"    font-family: Rubik;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.Sort1.setObjectName("Sort1")
        self.Sort2 = QtWidgets.QPushButton(self.SortingOption)
        self.Sort2.setGeometry(QtCore.QRect(10, 10, 251, 41))
        self.Sort2.setStyleSheet("#Sort2{\n"
"    font-family: Rubik;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.Sort2.setObjectName("Sort2")
        self.MainSettings = QtWidgets.QPushButton(self.MainSection)
        self.MainSettings.setGeometry(QtCore.QRect(1710, 20, 41, 41))
        self.MainSettings.setStyleSheet("#MainSettings{\n"
"    border : none;\n"
"}")
        self.MainSettings.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../img/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MainSettings.setIcon(icon3)
        self.MainSettings.setObjectName("MainSettings")
        self.Actions_2 = QtWidgets.QWidget(self.MainSection)
        self.Actions_2.setGeometry(QtCore.QRect(1490, 60, 271, 171))
        self.Actions_2.setStyleSheet("#Actions_2{\n"
"    border: 2px solid #052659;\n"
"    background-color: #D0E3FF;\n"
"    border-radius: 17px;\n"
"}")
        self.Actions_2.setObjectName("Actions_2")
        self.BoardTitle_4 = QtWidgets.QLabel(self.Actions_2)
        self.BoardTitle_4.setGeometry(QtCore.QRect(20, 20, 101, 21))
        self.BoardTitle_4.setStyleSheet("#BoardTitle_4{\n"
"    font-family: Rubik;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.BoardTitle_4.setObjectName("BoardTitle_4")
        self.Favorite_2 = QtWidgets.QPushButton(self.Actions_2)
        self.Favorite_2.setGeometry(QtCore.QRect(10, 50, 251, 41))
        self.Favorite_2.setStyleSheet("#Favorite_2{\n"
"    font-family: Rubik;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.Favorite_2.setIcon(icon1)
        self.Favorite_2.setObjectName("Favorite_2")
        self.DeleteProject_2 = QtWidgets.QPushButton(self.Actions_2)
        self.DeleteProject_2.setGeometry(QtCore.QRect(10, 100, 251, 41))
        self.DeleteProject_2.setStyleSheet("#DeleteProject_2{\n"
"    font-family: Rubik;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.DeleteProject_2.setIcon(icon2)
        self.DeleteProject_2.setObjectName("DeleteProject_2")
        self.Containerforwords.raise_()
        self.YourProject.raise_()
        self.AddProjectButton.raise_()
        self.FavoriteProject.raise_()
        self.QuickAccess.raise_()
        self.BoardName.raise_()
        self.ContainerForBoards.raise_()
        self.ContainerForBoards_2.raise_()
        self.AddingProject.raise_()
        self.Sorting.raise_()
        self.Actions.raise_()
        self.SortingOption.raise_()
        self.MainSettings.raise_()
        self.Actions_2.raise_()
        self.Searchbar = QtWidgets.QWidget(Ergo)
        self.Searchbar.setGeometry(QtCore.QRect(130, 0, 1851, 61))
        self.Searchbar.setStyleSheet("#Searchbar{\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #5483B3, stop:1 #4D6D8F);\n"
"    border : none;\n"
"}")
        self.Searchbar.setObjectName("Searchbar")
        self.SearchBoard = QtWidgets.QLineEdit(self.Searchbar)
        self.SearchBoard.setGeometry(QtCore.QRect(20, 20, 811, 31))
        self.SearchBoard.setStyleSheet("#SearchBoard{\n"
"    border-radius : 10px;\n"
"    font-family : Rubik;\n"
"    color : #6C6C6C;\n"
"    font-size : 15px;\n"
"}")
        self.SearchBoard.setObjectName("SearchBoard")
        self.SmileyFace = QtWidgets.QLabel(self.Searchbar)
        self.SmileyFace.setGeometry(QtCore.QRect(1620, 10, 41, 41))
        self.SmileyFace.setText("")
        self.SmileyFace.setPixmap(QtGui.QPixmap("../../img/smileyface.png"))
        self.SmileyFace.setScaledContents(True)
        self.SmileyFace.setObjectName("SmileyFace")
        self.UserErgo = QtWidgets.QLabel(self.Searchbar)
        self.UserErgo.setGeometry(QtCore.QRect(1660, 20, 71, 21))
        self.UserErgo.setStyleSheet("#UserErgo{\n"
"    font-family : Rubik;\n"
"    font-size : 13px;\n"
"}")
        self.UserErgo.setObjectName("UserErgo")
        self.SearchButton = QtWidgets.QPushButton(self.Searchbar)
        self.SearchButton.setGeometry(QtCore.QRect(20, 20, 41, 31))
        self.SearchButton.setStyleSheet("#SearchButton{\n"
"    border : none;\n"
"}")
        self.SearchButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../img/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SearchButton.setIcon(icon4)
        self.SearchButton.setObjectName("SearchButton")
        self.Navbar.raise_()
        self.Searchbar.raise_()
        self.MainSection.raise_()

        self.retranslateUi(Ergo)
        QtCore.QMetaObject.connectSlotsByName(Ergo)

    def retranslateUi(self, Ergo):
        _translate = QtCore.QCoreApplication.translate
        Ergo.setWindowTitle(_translate("Ergo", "Ergo"))
        self.BoardName.setText(_translate("Ergo", "Mobile Developement"))
        self.Welcome.setText(_translate("Ergo", "Welcome!"))
        self.WelcomeProject.setText(_translate("Ergo", "This section will show you every projects you have on this board"))
        self.YourProject.setText(_translate("Ergo", "Your Projects"))
        self.AddProjectButton.setText(_translate("Ergo", "+ Add New Project"))
        self.FavoriteProject.setText(_translate("Ergo", "Favorite Projects"))
        self.QuickAccess.setText(_translate("Ergo", "Get quick access to your favorite project by giving a star on them"))
        self.Board2.setText(_translate("Ergo", "Build UX"))
        self.Project1.setText(_translate("Ergo", "Build UI"))
        self.Board3.setText(_translate("Ergo", "Integrate"))
        self.Board1_2.setText(_translate("Ergo", "Build UI"))
        self.Board1_3.setText(_translate("Ergo", "Build UI"))
        self.Board1_4.setText(_translate("Ergo", "Build UI"))
        self.Board1_5.setText(_translate("Ergo", "Build UI"))
        self.Board1_6.setText(_translate("Ergo", "Build UI"))
        self.Board1_7.setText(_translate("Ergo", "Build UI"))
        self.Favp1.setText(_translate("Ergo", "Mobile Development"))
        self.BoardTitle.setText(_translate("Ergo", "Project Title"))
        self.BoardTitle_2.setText(_translate("Ergo", "Project Title is required"))
        self.CreateBoard.setText(_translate("Ergo", "Create Board"))
        self.Sorting.setText(_translate("Ergo", "Sort By"))
        self.BoardTitle_3.setText(_translate("Ergo", "Actions"))
        self.Favorite.setText(_translate("Ergo", " Add to Favorite"))
        self.DeleteProject.setText(_translate("Ergo", " Delete Project"))
        self.Sort1.setText(_translate("Ergo", "Sort Descending"))
        self.Sort2.setText(_translate("Ergo", "Sort Ascending"))
        self.BoardTitle_4.setText(_translate("Ergo", "Actions"))
        self.Favorite_2.setText(_translate("Ergo", " Add to Favorite"))
        self.DeleteProject_2.setText(_translate("Ergo", " Delete Board"))
        self.SearchBoard.setText(_translate("Ergo", "          Search Your Board"))
        self.UserErgo.setText(_translate("Ergo", "  User Ergo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ergo = QtWidgets.QWidget()
    ui = Ui_Ergo()
    ui.setupUi(Ergo)
    Ergo.show()
    sys.exit(app.exec_())
