# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'board.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BoardPage(object):
    def setupUi(self, BoardPage):
        BoardPage.setObjectName("BoardPage")
        BoardPage.resize(586, 442)
        BoardPage.setStyleSheet("")
        self.Navbar = QtWidgets.QWidget(BoardPage)
        self.Navbar.setGeometry(QtCore.QRect(0, 0, 111, 451))
        self.Navbar.setStyleSheet("#Navbar{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #5483B3, stop:1 #24384D);\n"
"}")
        self.Navbar.setObjectName("Navbar")
        self.LogoErgo = QtWidgets.QLabel(self.Navbar)
        self.LogoErgo.setGeometry(QtCore.QRect(-20, 10, 141, 141))
        self.LogoErgo.setStyleSheet("")
        self.LogoErgo.setText("")
        self.LogoErgo.setPixmap(QtGui.QPixmap("C:/Users/Kristian/Downloads/ego2.png"))
        self.LogoErgo.setScaledContents(True)
        self.LogoErgo.setObjectName("LogoErgo")
        self.Mainsection = QtWidgets.QWidget(BoardPage)
        self.Mainsection.setGeometry(QtCore.QRect(110, 40, 491, 421))
        self.Mainsection.setStyleSheet("#Mainsection{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #DAD9D8, stop:1 #97C9ED);\n"
"}")
        self.Mainsection.setObjectName("Mainsection")
        self.BoardName = QtWidgets.QLabel(self.Mainsection)
        self.BoardName.setGeometry(QtCore.QRect(20, 10, 311, 31))
        self.BoardName.setStyleSheet("#BoardName{\n"
"    font: 30px \"Roboto\";\n"
"    color: #5483B3;\n"
"    font-weight: bold;\n"
"}")
        self.BoardName.setObjectName("BoardName")
        self.ContainerWords = QtWidgets.QWidget(self.Mainsection)
        self.ContainerWords.setGeometry(QtCore.QRect(10, 50, 351, 61))
        self.ContainerWords.setStyleSheet("#ContainerWords{\n"
"    border: 2px solid #9FB0CC;\n"
"    background-color: #ECECF3;\n"
"    border-radius: 17px;\n"
"}")
        self.ContainerWords.setObjectName("ContainerWords")
        self.Welcome = QtWidgets.QLabel(self.ContainerWords)
        self.Welcome.setGeometry(QtCore.QRect(10, 10, 311, 21))
        self.Welcome.setStyleSheet("#Welcome {\n"
"    font: bold 15px \"Roboto\";\n"
"    color: #7DA0CA;\n"
"}")
        self.Welcome.setObjectName("Welcome")
        self.Greetings = QtWidgets.QLabel(self.ContainerWords)
        self.Greetings.setGeometry(QtCore.QRect(10, 40, 341, 16))
        self.Greetings.setStyleSheet("#Greetings{\n"
"    font: bold 10px \"Roboto\";\n"
"    color: #7DA0CA;\n"
"}")
        self.Greetings.setObjectName("Greetings")
        self.ProjectsOnBoard = QtWidgets.QLabel(self.Mainsection)
        self.ProjectsOnBoard.setGeometry(QtCore.QRect(20, 130, 151, 31))
        self.ProjectsOnBoard.setStyleSheet("#ProjectsOnBoard{\n"
"    font: 20px \"Roboto\";\n"
"    color: #5483B3;\n"
"    font-weight: bold;\n"
"}")
        self.ProjectsOnBoard.setObjectName("ProjectsOnBoard")
        self.SortOption = QtWidgets.QPushButton(self.Mainsection)
        self.SortOption.setGeometry(QtCore.QRect(20, 180, 111, 24))
        self.SortOption.setStyleSheet("#SortOption{\n"
"    border: 2px solid #9FB0CC;\n"
"    background-color: #ECECF3;\n"
"    border-radius: 10px;\n"
"    font-family: \"Roboto\";\n"
"    font-size: 11px;\n"
"    font-weight: bold;\n"
"    color: #5483B3;\n"
"}")
        self.SortOption.setObjectName("SortOption")
        self.Project1 = QtWidgets.QPushButton(self.Mainsection)
        self.Project1.setGeometry(QtCore.QRect(20, 210, 131, 51))
        self.Project1.setStyleSheet("#Project1{\n"
"    background-color: #F6F6F6;\n"
"    border-radius: 10px;\n"
"    font-family: \"Roboto\";\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"   color: #5483B3;\n"
"}")
        self.Project1.setObjectName("Project1")
        self.FavoriteBoards = QtWidgets.QLabel(self.Mainsection)
        self.FavoriteBoards.setGeometry(QtCore.QRect(20, 280, 171, 31))
        self.FavoriteBoards.setStyleSheet("#FavoriteBoards{\n"
"    font: 20px \"Roboto\";\n"
"    color: #5483B3;\n"
"    font-weight: bold;\n"
"}")
        self.FavoriteBoards.setObjectName("FavoriteBoards")
        self.DescFav = QtWidgets.QLabel(self.Mainsection)
        self.DescFav.setGeometry(QtCore.QRect(20, 310, 351, 31))
        self.DescFav.setStyleSheet("#DescFav\n"
"{\n"
"    font: 10px \"Roboto\";\n"
"    color: #5483B3;\n"
"    font-weight: bold;\n"
"}")
        self.DescFav.setObjectName("DescFav")
        self.FavProject1 = QtWidgets.QPushButton(self.Mainsection)
        self.FavProject1.setGeometry(QtCore.QRect(20, 340, 131, 51))
        self.FavProject1.setStyleSheet("#FavProject1{\n"
"    background-color: #F6F6F6;\n"
"    border-radius: 10px;\n"
"    font-family: \"Roboto\";\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"   color: #5483B3;\n"
"}")
        self.FavProject1.setObjectName("FavProject1")
        self.AddingProjects = QtWidgets.QPushButton(self.Mainsection)
        self.AddingProjects.setGeometry(QtCore.QRect(140, 180, 121, 24))
        self.AddingProjects.setStyleSheet("#AddingProjects{\n"
"    border: 2px solid #9FB0CC;\n"
"    background-color: #ECECF3;\n"
"    border-radius: 10px;\n"
"    font-family: \"Roboto\";\n"
"    font-size: 11px;\n"
"    font-weight: bold;\n"
"    color: #5483B3;\n"
"}")
        self.AddingProjects.setObjectName("AddingProjects")
        self.SortBy = QtWidgets.QLabel(self.Mainsection)
        self.SortBy.setGeometry(QtCore.QRect(30, 160, 51, 20))
        self.SortBy.setStyleSheet("#SortBy{\n"
"    font: 10px \"Roboto\";\n"
"    color: #5483B3;\n"
"    font-weight: bold;\n"
"}")
        self.SortBy.setObjectName("SortBy")
        self.SettingsForBoard = QtWidgets.QPushButton(self.Mainsection)
        self.SettingsForBoard.setGeometry(QtCore.QRect(430, 10, 31, 24))
        self.SettingsForBoard.setStyleSheet("#SettingsForBoard{\n"
"    border : none;\n"
"}")
        self.SettingsForBoard.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Kristian/Downloads/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SettingsForBoard.setIcon(icon)
        self.SettingsForBoard.setObjectName("SettingsForBoard")
        self.ContainerWords.raise_()
        self.ProjectsOnBoard.raise_()
        self.SortOption.raise_()
        self.Project1.raise_()
        self.FavoriteBoards.raise_()
        self.DescFav.raise_()
        self.BoardName.raise_()
        self.FavProject1.raise_()
        self.AddingProjects.raise_()
        self.SortBy.raise_()
        self.SettingsForBoard.raise_()
        self.Searchbar = QtWidgets.QWidget(BoardPage)
        self.Searchbar.setGeometry(QtCore.QRect(100, 0, 551, 41))
        self.Searchbar.setStyleSheet("#Searchbar{\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #5483B3, stop:1 #4D6D8F);\n"
"}")
        self.Searchbar.setObjectName("Searchbar")
        self.SearchingInput = QtWidgets.QLineEdit(self.Searchbar)
        self.SearchingInput.setGeometry(QtCore.QRect(10, 10, 371, 22))
        self.SearchingInput.setStyleSheet("#SearchingInput{\n"
"    border-radius : 10px;\n"
"    font-family : Rubik;\n"
"    color : #6C6C6C;\n"
"    font-size : 10px;\n"
"}")
        self.SearchingInput.setObjectName("SearchingInput")
        self.LogoUser = QtWidgets.QLabel(self.Searchbar)
        self.LogoUser.setGeometry(QtCore.QRect(400, 10, 21, 21))
        self.LogoUser.setText("")
        self.LogoUser.setPixmap(QtGui.QPixmap("C:/Users/Kristian/Downloads/smileyface.png"))
        self.LogoUser.setScaledContents(True)
        self.LogoUser.setObjectName("LogoUser")
        self.UserErgo = QtWidgets.QLabel(self.Searchbar)
        self.UserErgo.setGeometry(QtCore.QRect(420, 10, 51, 16))
        self.UserErgo.setStyleSheet("#UserErgo{\n"
"    font-family : Rubik;\n"
"    font-size : 9px;\n"
"}")
        self.UserErgo.setObjectName("UserErgo")
        self.SearchButton = QtWidgets.QPushButton(self.Searchbar)
        self.SearchButton.setGeometry(QtCore.QRect(20, 10, 31, 21))
        self.SearchButton.setStyleSheet("#SearchButton{\n"
"    border : none;\n"
"}")
        self.SearchButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/Kristian/Downloads/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SearchButton.setIcon(icon1)
        self.SearchButton.setObjectName("SearchButton")

        self.retranslateUi(BoardPage)
        QtCore.QMetaObject.connectSlotsByName(BoardPage)

    def retranslateUi(self, BoardPage):
        _translate = QtCore.QCoreApplication.translate
        BoardPage.setWindowTitle(_translate("BoardPage", "Ergo"))
        self.BoardName.setText(_translate("BoardPage", "Mobile Development"))
        self.Welcome.setText(_translate("BoardPage", "Welcome to Mobile Development Board !"))
        self.Greetings.setText(_translate("BoardPage", "This section will show you every projects you have on this board"))
        self.ProjectsOnBoard.setText(_translate("BoardPage", "Your Projects"))
        self.SortOption.setText(_translate("BoardPage", "Select an option"))
        self.Project1.setText(_translate("BoardPage", "Mobile Development"))
        self.FavoriteBoards.setText(_translate("BoardPage", "Favorite Boards"))
        self.DescFav.setText(_translate("BoardPage", "Get quick access to your favorite boards by giving a star on them"))
        self.FavProject1.setText(_translate("BoardPage", "Mobile Development"))
        self.AddingProjects.setText(_translate("BoardPage", "+ Add New Project"))
        self.SortBy.setText(_translate("BoardPage", "Sort by"))
        self.SearchingInput.setText(_translate("BoardPage", "              Search Your Board"))
        self.UserErgo.setText(_translate("BoardPage", "  User Ergo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BoardPage = QtWidgets.QWidget()
    ui = Ui_BoardPage()
    ui.setupUi(BoardPage)
    BoardPage.show()
    sys.exit(app.exec_())
