# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ergo(object):
    def setupUi(self, Ergo):
        Ergo.setObjectName("Ergo")
        Ergo.resize(1863, 1071)
        self.Navbar = QtWidgets.QWidget(Ergo)
        self.Navbar.setGeometry(QtCore.QRect(0, 0, 111, 1080))
        self.Navbar.setStyleSheet("#Navbar{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #5483B3, stop:1 #24384D);\n"
"}")
        self.Navbar.setObjectName("Navbar")
        self.label_3 = QtWidgets.QLabel(self.Navbar)
        self.label_3.setGeometry(QtCore.QRect(-20, 10, 141, 141))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("img\\logoergo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.MainSection = QtWidgets.QWidget(Ergo)
        self.MainSection.setGeometry(QtCore.QRect(110, 40, 1920, 1080))
        self.MainSection.setStyleSheet("#MainSection{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #DAD9D8, stop:1 #97C9ED);\n"
"}")
        self.MainSection.setObjectName("MainSection")
        self.back = QtWidgets.QPushButton(self.MainSection)
        self.back.setGeometry(QtCore.QRect(0, 0, 100, 31))
        self.back.setStyleSheet("#back {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: #5483B3;\n"
"}")
        self.back.setObjectName("back")
        self.namaboard = QtWidgets.QPushButton(self.MainSection)
        self.namaboard.setGeometry(QtCore.QRect(100, 0, 120, 31))
        self.namaboard.setStyleSheet("#namaboard {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color : #5483B3\n"
"}")
        self.namaboard.setObjectName("namaboard")
        self.namaproject = QtWidgets.QPushButton(self.MainSection)
        #ditaruh 10 pixel setelah namaboard berakhir
        self.namaproject.setGeometry(QtCore.QRect(220, 0, 120, 31))
        self.namaproject.setStyleSheet("#namaboard {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color : #5483B3\n"
"}")
        self.namaproject.setObjectName("namaboard")
        self.Greetings = QtWidgets.QLabel(self.MainSection)
        self.Greetings.setGeometry(QtCore.QRect(20, 16, 581, 71))
        self.Greetings.setStyleSheet("#Greetings{\n"
"    font: 30px \"Roboto\";\n"
"    color: #5483B3;\n"
"    font-weight: bold;\n"
"}")
        self.Greetings.setObjectName("Greetings")
        self.Containerforwords = QtWidgets.QWidget(self.MainSection)
        self.Containerforwords.setGeometry(QtCore.QRect(20, 100, 161, 61))
        self.Containerforwords.setStyleSheet("#Containerforwords{\n"
"    border: 2px solid #9FB0CC;\n"
"    background-color: #ECECF3;\n"
"    border-radius: 17px;\n"
"}")
        self.Containerforwords.setObjectName("Containerforwords")
        self.label = QtWidgets.QLabel(self.Containerforwords)
        self.label.setGeometry(QtCore.QRect(30, 20, 151, 21))
        self.label.setStyleSheet("#label {\n"
"    font: bold 15px \"Roboto\";\n"
"    color: #7DA0CA;\n"
"}")
        self.label.setObjectName("label")
        self.Greetings_2 = QtWidgets.QLabel(self.MainSection)
        self.Greetings_2.setGeometry(QtCore.QRect(20, 160, 311, 51))
        self.Greetings_2.setStyleSheet("#Greetings_2{\n"
"    font: 20px \"Roboto\";\n"
"    color: #5483B3;\n"
"    font-weight: bold;\n"
"}")
        self.Greetings_2.setObjectName("Greetings_2")
        self.pushButton = QtWidgets.QPushButton(self.MainSection)
        self.pushButton.setGeometry(QtCore.QRect(400, 260, 161, 31))
        self.pushButton.setStyleSheet("#pushButton{\n"
"    border: 2px solid #9FB0CC;\n"
"    background-color: #ECECF3;\n"
"    border-radius: 10px;\n"
"    font-family: \"Roboto\";\n"
"    font-size: 11px;\n"
"    font-weight: bold;\n"
"    color: #5483B3;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.MainSection)
        self.label_2.setGeometry(QtCore.QRect(20, 220, 91, 31))
        self.label_2.setObjectName("label_2")
        self.Containerforwords_2 = QtWidgets.QWidget(self.MainSection)
        self.Containerforwords_2.setGeometry(QtCore.QRect(20, 250, 161, 41))
        self.Containerforwords_2.setStyleSheet("#Containerforwords_2{\n"
"    border: 2px solid #9FB0CC;\n"
"    background-color: #ECECF3;\n"
"    border-radius: 10px;\n"
"}")
        self.Containerforwords_2.setObjectName("Containerforwords_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.Containerforwords_2)
        self.comboBox_2.setGeometry(QtCore.QRect(30, 10, 101, 20))
        self.comboBox_2.setStyleSheet("#comboBox_2{\n"
"    background-color: #ECECF3;\n"
"    border : none;\n"
"    font-size:9pt;\n"
"    font-weight:600;\n"
"    color:#5483b3;\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.Containerforwords_4 = QtWidgets.QWidget(self.MainSection)
        self.Containerforwords_4.setGeometry(QtCore.QRect(200, 250, 181, 41))
        self.Containerforwords_4.setStyleSheet("#Containerforwords_4{\n"
"    border: 2px solid #9FB0CC;\n"
"    background-color: #ECECF3;\n"
"    border-radius: 10px;\n"
"}")
        self.Containerforwords_4.setObjectName("Containerforwords_4")
        self.comboBox = QtWidgets.QComboBox(self.Containerforwords_4)
        self.comboBox.setGeometry(QtCore.QRect(40, 10, 101, 22))
        self.comboBox.setStyleSheet("#comboBox{\n"
"    background-color: #ECECF3;\n"
"    border : none;\n"
"    font-size:9pt;\n"
"    font-weight:600;\n"
"    color:#5483b3;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.progressBar = QtWidgets.QProgressBar(self.MainSection)
        self.progressBar.setGeometry(QtCore.QRect(30, 890, 1661, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setKerning(True)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar.setObjectName("progressBar")
        self.label_8 = QtWidgets.QLabel(self.MainSection)
        self.label_8.setGeometry(QtCore.QRect(200, 220, 121, 31))
        self.label_8.setObjectName("label_8")
        self.Greetings_3 = QtWidgets.QLabel(self.MainSection)
        self.Greetings_3.setGeometry(QtCore.QRect(30, 790, 451, 51))
        self.Greetings_3.setStyleSheet("#Greetings_3{\n"
"    font: 20px \"Roboto\";\n"
"    color: #5483B3;\n"
"    font-weight: bold;\n"
"}")
        self.Greetings_3.setObjectName("Greetings_3")
        self.label_9 = QtWidgets.QLabel(self.MainSection)
        self.label_9.setGeometry(QtCore.QRect(30, 840, 521, 51))
        self.label_9.setObjectName("label_9")
        self.scrollArea = QtWidgets.QScrollArea(self.MainSection)
        self.scrollArea.setGeometry(QtCore.QRect(20, 310, 1681, 471))
        self.scrollArea.setStyleSheet("#scrollArea {\n"
"    border: 2px solid #9FB0CC;\n"
"    background-color: #ECECF3;\n"
"    border-radius: 17px;\n"
"}\n"
"\n"
"#widget, #widget_2, #widget_3, #widget_4 {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1677, 467))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        spacerItem = QtWidgets.QSpacerItem(83, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_13 = QtWidgets.QLabel(self.widget_2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.label_14 = QtWidgets.QLabel(self.widget_2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget_4)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_2.addWidget(self.checkBox_2)
        self.label_15 = QtWidgets.QLabel(self.widget_4)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_2.addWidget(self.label_15)
        spacerItem4 = QtWidgets.QSpacerItem(83, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label_17 = QtWidgets.QLabel(self.widget_4)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_2.addWidget(self.label_17)
        spacerItem5 = QtWidgets.QSpacerItem(83, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.label_19 = QtWidgets.QLabel(self.widget_4)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_2.addWidget(self.label_19)
        spacerItem6 = QtWidgets.QSpacerItem(82, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.label_16 = QtWidgets.QLabel(self.widget_4)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_2.addWidget(self.label_16)
        spacerItem7 = QtWidgets.QSpacerItem(83, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.label_18 = QtWidgets.QLabel(self.widget_4)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_2.addWidget(self.label_18)
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget_3)
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_3.addWidget(self.checkBox_3)
        self.label_20 = QtWidgets.QLabel(self.widget_3)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_3.addWidget(self.label_20)
        spacerItem8 = QtWidgets.QSpacerItem(83, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.label_22 = QtWidgets.QLabel(self.widget_3)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_3.addWidget(self.label_22)
        spacerItem9 = QtWidgets.QSpacerItem(83, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.label_24 = QtWidgets.QLabel(self.widget_3)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_3.addWidget(self.label_24)
        spacerItem10 = QtWidgets.QSpacerItem(82, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.label_21 = QtWidgets.QLabel(self.widget_3)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_3.addWidget(self.label_21)
        spacerItem11 = QtWidgets.QSpacerItem(83, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.label_23 = QtWidgets.QLabel(self.widget_3)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_3.addWidget(self.label_23)
        self.verticalLayout.addWidget(self.widget_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tambahTask = QtWidgets.QWidget(self.MainSection)
        self.tambahTask.setGeometry(QtCore.QRect(570, 80, 511, 381))
        self.tambahTask.setStyleSheet("#tambahTask {\n"
"    background-color: rgb(208, 228, 255);\n"
"    border-color: rgb(7, 36, 78);\n"
"    border-width : 1.2px;\n"
"    border-style:inset;\n"
"    border-radius:12;\n"
"}\n"
"\n"
"#textEdit {\n"
"    border: 1px;\n"
"    border-radius:10px;\n"
"    background-color: rgb(255, 255, 255); \n"
"}\n"
"\n"
"#label_25 {\n"
"    textEdit->plainText().isEmpty()\n"
"}\n"
"\n"
"#ComboBox_3 {\n"
"    model: [\"High\", \"Medium\", \"Low\"]\n"
"}")
        self.tambahTask.setObjectName("tambahTask")
        self.pushButton_2 = QtWidgets.QPushButton(self.tambahTask)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 326, 81, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit = QtWidgets.QTextEdit(self.tambahTask)
        self.textEdit.setGeometry(QtCore.QRect(20, 46, 191, 31))
        self.textEdit.setAutoFillBackground(False)
        self.textEdit.setObjectName("textEdit")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.tambahTask)
        self.dateTimeEdit.setGeometry(QtCore.QRect(310, 46, 141, 31))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_6 = QtWidgets.QLabel(self.tambahTask)
        self.label_6.setGeometry(QtCore.QRect(60, 10, 111, 41))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tambahTask)
        self.label_7.setGeometry(QtCore.QRect(330, 10, 101, 41))
        self.label_7.setObjectName("label_7")
        self.label_25 = QtWidgets.QLabel(self.tambahTask)
        self.label_25.setGeometry(QtCore.QRect(10, 70, 211, 41))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tambahTask)
        self.label_26.setGeometry(QtCore.QRect(20, 110, 121, 31))
        self.label_26.setObjectName("label_26")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tambahTask)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 136, 471, 151))
        self.textEdit_2.setAutoFillBackground(False)
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_27 = QtWidgets.QLabel(self.tambahTask)
        self.label_27.setGeometry(QtCore.QRect(20, 281, 111, 31))
        self.label_27.setObjectName("label_27")
        self.comboBox_3 = QtWidgets.QComboBox(self.tambahTask)
        self.comboBox_3.setGeometry(QtCore.QRect(20, 317, 191, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(0, "")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.pushButton_4 = QtWidgets.QPushButton(self.tambahTask)
        self.pushButton_4.setGeometry(QtCore.QRect(420, 326, 71, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.editTask = QtWidgets.QWidget(self.MainSection)
        self.editTask.setGeometry(QtCore.QRect(570, 80, 681, 381))
        self.editTask.setStyleSheet("#editTask {\n"
"    background-color: rgb(208, 228, 255);\n"
"    border-color: rgb(7, 36, 78);\n"
"    border-width : 1.2px;\n"
"    border-style:inset;\n"
"    border-radius:12;\n"
"}\n"
"\n"
"#textEdit_3 {\n"
"    border: 1px;\n"
"    border-radius:10px;\n"
"    background-color: rgb(255, 255, 255); \n"
"}\n"
"\n"
"#label_31 {\n"
"    textEdit_3->plainText().isEmpty()\n"
"}\n"
"\n"
"#ComboBox_4 {\n"
"    model: [\"High\", \"Medium\", \"Low\"]\n"
"}")
        self.editTask.setObjectName("editTask")
        self.pushButton_5 = QtWidgets.QPushButton(self.editTask)
        self.pushButton_5.setGeometry(QtCore.QRect(470, 326, 81, 21))
        self.pushButton_5.setObjectName("pushButton_5")
        self.textEdit_3 = QtWidgets.QTextEdit(self.editTask)
        self.textEdit_3.setGeometry(QtCore.QRect(20, 46, 191, 31))
        self.textEdit_3.setAutoFillBackground(False)
        self.textEdit_3.setObjectName("textEdit_3")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.editTask)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(270, 46, 141, 31))
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.label_29 = QtWidgets.QLabel(self.editTask)
        self.label_29.setGeometry(QtCore.QRect(60, 10, 111, 41))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.editTask)
        self.label_30.setGeometry(QtCore.QRect(290, 10, 101, 41))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.editTask)
        self.label_31.setGeometry(QtCore.QRect(10, 70, 211, 41))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.editTask)
        self.label_32.setGeometry(QtCore.QRect(20, 110, 121, 31))
        self.label_32.setObjectName("label_32")
        self.textEdit_4 = QtWidgets.QTextEdit(self.editTask)
        self.textEdit_4.setGeometry(QtCore.QRect(20, 136, 641, 151))
        self.textEdit_4.setAutoFillBackground(False)
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_33 = QtWidgets.QLabel(self.editTask)
        self.label_33.setGeometry(QtCore.QRect(20, 281, 111, 31))
        self.label_33.setObjectName("label_33")
        self.comboBox_4 = QtWidgets.QComboBox(self.editTask)
        self.comboBox_4.setGeometry(QtCore.QRect(20, 317, 191, 31))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(0, "")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.pushButton_6 = QtWidgets.QPushButton(self.editTask)
        self.pushButton_6.setGeometry(QtCore.QRect(580, 326, 71, 21))
        self.pushButton_6.setObjectName("pushButton_6")
        self.comboBox_5 = QtWidgets.QComboBox(self.editTask)
        self.comboBox_5.setGeometry(QtCore.QRect(460, 46, 191, 31))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_34 = QtWidgets.QLabel(self.editTask)
        self.label_34.setGeometry(QtCore.QRect(500, 10, 101, 41))
        self.label_34.setObjectName("label_34")
        self.back.raise_()
        self.Containerforwords_2.raise_()
        self.Containerforwords.raise_()
        self.Greetings_2.raise_()
        self.pushButton.raise_()
        self.Greetings.raise_()
        self.label_2.raise_()
        self.Containerforwords_4.raise_()
        self.progressBar.raise_()
        self.label_8.raise_()
        self.Greetings_3.raise_()
        self.label_9.raise_()
        self.scrollArea.raise_()
        self.tambahTask.raise_()
        self.editTask.raise_()
        self.Searchbar = QtWidgets.QWidget(Ergo)
        self.Searchbar.setGeometry(QtCore.QRect(100, 0, 1920, 41))
        self.Searchbar.setStyleSheet("#Searchbar{\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #5483B3, stop:1 #4D6D8F);\n"
"}")
        self.Searchbar.setObjectName("Searchbar")
        self.lineEdit = QtWidgets.QLineEdit(self.Searchbar)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 691, 22))
        self.lineEdit.setStyleSheet("#lineEdit{\n"
"    border-radius : 10px;\n"
"    font-family : Rubik;\n"
"    color : #6C6C6C;\n"
"    font-size : 10px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.Searchbar)
        self.label_4.setGeometry(QtCore.QRect(1660, 10, 21, 21))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("img\\smileyface.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Searchbar)
        self.label_5.setGeometry(QtCore.QRect(1690, 10, 51, 16))
        self.label_5.setStyleSheet("#label_5{\n"
"    font-family : Rubik;\n"
"    font-size : 9px;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.Searchbar)
        self.pushButton_3.setGeometry(QtCore.QRect(700, 10, 31, 21))
        self.pushButton_3.setStyleSheet("#pushButton_3{\n"
"    border : none;\n"
"}")
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img\\search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Ergo)
        QtCore.QMetaObject.connectSlotsByName(Ergo)

    def retranslateUi(self, Ergo):
        _translate = QtCore.QCoreApplication.translate
        Ergo.setWindowTitle(_translate("Ergo", "Ergo"))
        self.Greetings.setText(_translate("Ergo", "<html><head/><body><p><span style=\" font-size:36pt;\">Nama Project</span></p></body></html>"))
        self.label.setText(_translate("Ergo", "<html><head/><body><p><span style=\" font-size:12pt;\">Welcome!</span></p></body></html>"))
        self.Greetings_2.setText(_translate("Ergo", "<html><head/><body><p><span style=\" font-size:26pt;\">Your Task</span></p></body></html>"))
        self.pushButton.setText(_translate("Ergo", "+ Add New Task"))
        self.label_2.setText(_translate("Ergo", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#5483b3;\">Sort By</span></p></body></html>"))
        self.comboBox_2.setItemText(0, _translate("Ergo", "Ascending"))
        self.comboBox_2.setItemText(1, _translate("Ergo", "Descending"))
        self.comboBox.setItemText(0, _translate("Ergo", "Category"))
        self.comboBox.setItemText(1, _translate("Ergo", "Status"))
        self.label_8.setText(_translate("Ergo", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#5483b3;\">Group By</span></p></body></html>"))
        self.Greetings_3.setText(_translate("Ergo", "<html><head/><body><p><span style=\" font-size:22pt;\">Progress Bar</span></p></body></html>"))
        self.label_9.setText(_translate("Ergo", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#5483b3;\">Keep it up, you\'re almost there :D</span></p></body></html>"))
        self.label_10.setText(_translate("Ergo", "Nama Task 1"))
        self.label_11.setText(_translate("Ergo", "Status task 1"))
        self.label_12.setText(_translate("Ergo", "Category Task 1"))
        self.label_13.setText(_translate("Ergo", "Deadline Task 1"))
        self.label_14.setText(_translate("Ergo", "Description"))
        self.label_15.setText(_translate("Ergo", "Nama Task 1"))
        self.label_17.setText(_translate("Ergo", "Status task 1"))
        self.label_19.setText(_translate("Ergo", "Category Task 1"))
        self.label_16.setText(_translate("Ergo", "Deadline Task 1"))
        self.label_18.setText(_translate("Ergo", "Description"))
        self.label_20.setText(_translate("Ergo", "Nama Task 1"))
        self.label_22.setText(_translate("Ergo", "Status task 1"))
        self.label_24.setText(_translate("Ergo", "Category Task 1"))
        self.label_21.setText(_translate("Ergo", "Deadline Task 1"))
        self.label_23.setText(_translate("Ergo", "Description"))
        self.pushButton_2.setText(_translate("Ergo", "Create"))
        self.textEdit.setHtml(_translate("Ergo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>"))
        self.label_6.setText(_translate("Ergo", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#0a3675;\">Task Name</span></p></body></html>"))
        self.label_7.setText(_translate("Ergo", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#0a3675;\">Deadline</span></p></body></html>"))
        self.label_25.setText(_translate("Ergo", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#09336f;\">Task Name Required</span></p></body></html>"))
        self.label_26.setText(_translate("Ergo", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#0a3675;\">Description</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("Ergo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>"))
        self.label_27.setText(_translate("Ergo", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#0a3675;\">Category</span></p></body></html>"))
        self.comboBox_3.setItemText(1, _translate("Ergo", "High"))
        self.comboBox_3.setItemText(2, _translate("Ergo", "Medium"))
        self.comboBox_3.setItemText(3, _translate("Ergo", "Low"))
        self.pushButton_4.setText(_translate("Ergo", "Cancel"))
        self.pushButton_5.setText(_translate("Ergo", "Apply"))
        self.textEdit_3.setHtml(_translate("Ergo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>"))
        self.label_29.setText(_translate("Ergo", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#0a3675;\">Task Name</span></p></body></html>"))
        self.label_30.setText(_translate("Ergo", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#0a3675;\">Deadline</span></p></body></html>"))
        self.label_31.setText(_translate("Ergo", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#09336f;\">Task Name Required</span></p></body></html>"))
        self.label_32.setText(_translate("Ergo", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#0a3675;\">Description</span></p></body></html>"))
        self.textEdit_4.setHtml(_translate("Ergo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>"))
        self.label_33.setText(_translate("Ergo", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#0a3675;\">Category</span></p></body></html>"))
        self.comboBox_4.setItemText(1, _translate("Ergo", "High"))
        self.comboBox_4.setItemText(2, _translate("Ergo", "Medium"))
        self.comboBox_4.setItemText(3, _translate("Ergo", "Low"))
        self.pushButton_6.setText(_translate("Ergo", "Cancel"))
        self.comboBox_5.setItemText(0, _translate("Ergo", "Not Yet Started"))
        self.comboBox_5.setItemText(1, _translate("Ergo", "On Progress"))
        self.comboBox_5.setItemText(2, _translate("Ergo", "Completed"))
        self.label_34.setText(_translate("Ergo", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#0a3675;\">Status</span></p></body></html>"))
        self.lineEdit.setText(_translate("Ergo", ""))
        self.namaboard.setText(_translate("Ergo", "> board name"))
        self.namaproject.setText(_translate("Ergo", "> project name"))
        self.back.setText(_translate("Ergo", "Dashboard"))
        self.label_5.setText(_translate("Ergo", "  User Ergo"))

if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        Ergo = QtWidgets.QWidget()
        ui = Ui_Ergo()
        ui.setupUi(Ergo)
        Ergo.show()
        sys.exit(app.exec_())