# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'taskUIBaru.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ergo(object):
    def setupUi(self, Ergo):
        Ergo.setObjectName("Ergo")
        Ergo.resize(1920, 1080)
        self.Navbar = QtWidgets.QWidget(Ergo)
        self.Navbar.setGeometry(QtCore.QRect(0, 0, 201, 1081))
        self.Navbar.setStyleSheet("#Navbar{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #73c2fb, stop:1 #1560bd);\n"
"}")
        self.Navbar.setObjectName("Navbar")
        self.LogoErgo = QtWidgets.QLabel(self.Navbar)
        self.LogoErgo.setGeometry(QtCore.QRect(-15, 20, 221, 211))
        self.LogoErgo.setStyleSheet("")
        self.LogoErgo.setText("")
        self.LogoErgo.setPixmap(QtGui.QPixmap("../if2250-2024-k03-g04-ergo/img/logoergo.png"))
        self.LogoErgo.setScaledContents(True)
        self.LogoErgo.setObjectName("LogoErgo")
        self.BackToDashboard = QtWidgets.QPushButton(self.Navbar)
        self.BackToDashboard.setGeometry(QtCore.QRect(50, 230, 91, 31))
        self.BackToDashboard.setStyleSheet("#BackToDashboard\n"
" {\n"
"    font: 15px \"Roboto\";\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color:  #FFFFFF;\n"
"}")
        self.BackToDashboard.setObjectName("BackToDashboard")
        self.BackToYourBoard = QtWidgets.QPushButton(self.Navbar)
        self.BackToYourBoard.setGeometry(QtCore.QRect(50, 270, 91, 31))
        self.BackToYourBoard.setStyleSheet("#BackToYourBoard\n"
" {\n"
"    font: 15px \"Roboto\";\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color:  #FFFFFF;\n"
"}")
        self.BackToYourBoard.setObjectName("BackToYourBoard")
        self.MainSection = QtWidgets.QWidget(Ergo)
        self.MainSection.setGeometry(QtCore.QRect(200, 60, 1811, 1031))
        self.MainSection.setStyleSheet("#MainSection{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #97C9ED);\n"
"}")
        self.MainSection.setObjectName("MainSection")
        self.TaskNameTitle = QtWidgets.QLabel(self.MainSection)
        self.TaskNameTitle.setGeometry(QtCore.QRect(40, 40, 601, 71))
        self.TaskNameTitle.setStyleSheet("#TaskNameTitle{\n"
"    font: 45px \"Roboto\";\n"
"    color: #0E49B5;\n"
"    font-weight: bold;\n"
"}")
        self.TaskNameTitle.setObjectName("TaskNameTitle")
        self.Containerforwords = QtWidgets.QWidget(self.MainSection)
        self.Containerforwords.setGeometry(QtCore.QRect(30, 130, 621, 111))
        self.Containerforwords.setStyleSheet("#Containerforwords{\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #73c2fb, stop:1 #1560bd);\n"
"    border-radius: 15px;\n"
"}")
        self.Containerforwords.setObjectName("Containerforwords")
        self.Welcome = QtWidgets.QLabel(self.Containerforwords)
        self.Welcome.setGeometry(QtCore.QRect(20, 20, 171, 31))
        self.Welcome.setStyleSheet("#Welcome {\n"
"    font: bold 25px \"Roboto\";\n"
"    color: #FFFFFF;\n"
"}")
        self.Welcome.setObjectName("Welcome")
        self.WelcomingTitle = QtWidgets.QLabel(self.Containerforwords)
        self.WelcomingTitle.setGeometry(QtCore.QRect(20, 70, 591, 31))
        self.WelcomingTitle.setStyleSheet("#WelcomingTitle{\n"
"    font: bold 18px \"Roboto\";\n"
"    color: #FFFFFF\n"
"}")
        self.WelcomingTitle.setObjectName("WelcomingTitle")
        self.YourTask = QtWidgets.QLabel(self.MainSection)
        self.YourTask.setGeometry(QtCore.QRect(50, 300, 291, 51))
        self.YourTask.setStyleSheet("#YourTask{\n"
"    font: 40px \"Roboto\";\n"
"    color: #0E49B5;\n"
"    font-weight: bold;\n"
"}")
        self.YourTask.setObjectName("YourTask")
        self.AddNewTaskButton = QtWidgets.QPushButton(self.MainSection)
        self.AddNewTaskButton.setGeometry(QtCore.QRect(450, 370, 171, 31))
        self.AddNewTaskButton.setStyleSheet("#AddNewTaskButton{\n"
"    border : 1px solid #0047ab;\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 10px;\n"
"    font-family: \"Roboto\";\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #0197F6;\n"
"}")
        self.AddNewTaskButton.setObjectName("AddNewTaskButton")
        self.Sorting = QtWidgets.QPushButton(self.MainSection)
        self.Sorting.setGeometry(QtCore.QRect(50, 370, 171, 31))
        self.Sorting.setStyleSheet("#Sorting{\n"
"    border : 1px solid #0047ab;\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 10px;\n"
"    font-family: \"Roboto\";\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #0197F6;\n"
"}")
        self.Sorting.setObjectName("Sorting")
        self.BackToDashboardUpper = QtWidgets.QPushButton(self.MainSection)
        self.BackToDashboardUpper.setGeometry(QtCore.QRect(10, 0, 81, 31))
        self.BackToDashboardUpper.setStyleSheet("#BackToDashboardUpper{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color:  #0E49B5;;\n"
"}")
        self.BackToDashboardUpper.setObjectName("BackToDashboardUpper")
        self.widgetContainerTask = QtWidgets.QWidget(self.MainSection)
        self.widgetContainerTask.setGeometry(QtCore.QRect(40, 460, 1121, 531))
        self.widgetContainerTask.setStyleSheet("#widgetContainerTask{\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #73c2fb, stop:1 #1560bd);\n"
"    border-radius : 10px;\n"
"}")
        self.widgetContainerTask.setObjectName("widgetContainerTask")
        self.ContainerForTask = QtWidgets.QScrollArea(self.widgetContainerTask)
        self.ContainerForTask.setGeometry(QtCore.QRect(10, 10, 1101, 511))
        self.ContainerForTask.setStyleSheet("#ContainerForTask, QScrollArea QWidget{\n"
"    border-radius: 10px;\n"
"     background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #73c2fb, stop:1 #1560bd);\n"
"}")
        self.ContainerForTask.setWidgetResizable(True)
        self.ContainerForTask.setObjectName("ContainerForTask")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1101, 511))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.ContainerForSingleTask = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.ContainerForSingleTask.setGeometry(QtCore.QRect(0, 10, 1101, 71))
        self.ContainerForSingleTask.setStyleSheet("#ContainerForSingleTask{\n"
"    background-color : #FFFFFF\n"
"}")
        self.ContainerForSingleTask.setObjectName("ContainerForSingleTask")
        self.Task1Name = QtWidgets.QLabel(self.ContainerForSingleTask)
        self.Task1Name.setGeometry(QtCore.QRect(40, 25, 191, 20))
        self.Task1Name.setStyleSheet("#Task1Name{\n"
"    background-color : none;\n"
"font-family: \"Roboto\";\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #0E49B5;\n"
"}")
        self.Task1Name.setObjectName("Task1Name")
        self.Task1Status = QtWidgets.QLabel(self.ContainerForSingleTask)
        self.Task1Status.setGeometry(QtCore.QRect(260, 25, 181, 20))
        self.Task1Status.setStyleSheet("#Task1Status{\n"
"    background-color : none;\n"
"font-family: \"Roboto\";\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #0E49B5;\n"
"}")
        self.Task1Status.setObjectName("Task1Status")
        self.Task1Category = QtWidgets.QLabel(self.ContainerForSingleTask)
        self.Task1Category.setGeometry(QtCore.QRect(450, 25, 161, 20))
        self.Task1Category.setStyleSheet("#Task1Category{\n"
"    background-color : none;\n"
"font-family: \"Roboto\";\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #0E49B5;\n"
"}")
        self.Task1Category.setObjectName("Task1Category")
        self.Task1Deadline = QtWidgets.QLabel(self.ContainerForSingleTask)
        self.Task1Deadline.setGeometry(QtCore.QRect(620, 25, 221, 20))
        self.Task1Deadline.setStyleSheet("#Task1Deadline{\n"
"    background-color : none;\n"
"font-family: \"Roboto\";\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #0E49B5;\n"
"}")
        self.Task1Deadline.setObjectName("Task1Deadline")
        self.checkBoxTask1 = QtWidgets.QCheckBox(self.ContainerForSingleTask)
        self.checkBoxTask1.setGeometry(QtCore.QRect(10, 25, 21, 24))
        self.checkBoxTask1.setStyleSheet("#checkBoxTask1{\n"
"    background-color : none;\n"
"}")
        self.checkBoxTask1.setText("")
        self.checkBoxTask1.setObjectName("checkBoxTask1")
        self.Task1Description = QtWidgets.QTextBrowser(self.ContainerForSingleTask)
        self.Task1Description.setGeometry(QtCore.QRect(825, 0, 261, 71))
        self.Task1Description.setStyleSheet("#Task1Description{\n"
"    background-color : none;\n"
"font-family: \"Roboto\";\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    color: #0E49B5;\n"
"}")
        self.Task1Description.setObjectName("Task1Description")
        self.ContainerForSingleTask_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.ContainerForSingleTask_2.setGeometry(QtCore.QRect(0, 90, 1101, 71))
        self.ContainerForSingleTask_2.setStyleSheet("#ContainerForSingleTask_2{\n"
"    background-color : #FFFFFF\n"
"}")
        self.ContainerForSingleTask_2.setObjectName("ContainerForSingleTask_2")
        self.Task2Name = QtWidgets.QLabel(self.ContainerForSingleTask_2)
        self.Task2Name.setGeometry(QtCore.QRect(40, 25, 181, 20))
        self.Task2Name.setStyleSheet("#Task2Name{\n"
"    background-color : none;\n"
"font-family: \"Roboto\";\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #0E49B5;\n"
"}")
        self.Task2Name.setObjectName("Task2Name")
        self.Task2Status = QtWidgets.QLabel(self.ContainerForSingleTask_2)
        self.Task2Status.setGeometry(QtCore.QRect(260, 25, 181, 20))
        self.Task2Status.setStyleSheet("#Task2Status{\n"
"    background-color : none;\n"
"font-family: \"Roboto\";\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #0E49B5;\n"
"}")
        self.Task2Status.setObjectName("Task2Status")
        self.Task2Category = QtWidgets.QLabel(self.ContainerForSingleTask_2)
        self.Task2Category.setGeometry(QtCore.QRect(450, 25, 161, 20))
        self.Task2Category.setStyleSheet("#Task2Category{\n"
"    background-color : none;\n"
"font-family: \"Roboto\";\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #0E49B5;\n"
"}")
        self.Task2Category.setObjectName("Task2Category")
        self.Task2Deadline = QtWidgets.QLabel(self.ContainerForSingleTask_2)
        self.Task2Deadline.setGeometry(QtCore.QRect(620, 25, 221, 20))
        self.Task2Deadline.setStyleSheet("#Task2Deadline{\n"
"    background-color : none;\n"
"font-family: \"Roboto\";\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #0E49B5;\n"
"}")
        self.Task2Deadline.setObjectName("Task2Deadline")
        self.checkBoxTask2 = QtWidgets.QCheckBox(self.ContainerForSingleTask_2)
        self.checkBoxTask2.setGeometry(QtCore.QRect(10, 25, 21, 24))
        self.checkBoxTask2.setStyleSheet("#checkBoxTask2{\n"
"    background-color : none;\n"
"}")
        self.checkBoxTask2.setText("")
        self.checkBoxTask2.setObjectName("checkBoxTask2")
        self.Task2Description = QtWidgets.QTextBrowser(self.ContainerForSingleTask_2)
        self.Task2Description.setGeometry(QtCore.QRect(830, 0, 261, 71))
        self.Task2Description.setStyleSheet("#Task2Description{\n"
"    background-color : none;\n"
"font-family: \"Roboto\";\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    color: #0E49B5;\n"
"}")
        self.Task2Description.setObjectName("Task2Description")
        self.ContainerForTask.setWidget(self.scrollAreaWidgetContents)
        self.CurrentTaskUpper = QtWidgets.QLabel(self.MainSection)
        self.CurrentTaskUpper.setGeometry(QtCore.QRect(191, 5, 71, 21))
        self.CurrentTaskUpper.setStyleSheet("#CurrentTaskUpper{\n"
"    color : #5483B3\n"
"}")
        self.CurrentTaskUpper.setObjectName("CurrentTaskUpper")
        self.Grouping = QtWidgets.QPushButton(self.MainSection)
        self.Grouping.setGeometry(QtCore.QRect(250, 370, 171, 31))
        self.Grouping.setStyleSheet("#Grouping{\n"
"    border : 1px solid #0047ab;\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 10px;\n"
"    font-family: \"Roboto\";\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #0197F6;\n"
"}")
        self.Grouping.setObjectName("Grouping")
        self.GroupingOption = QtWidgets.QWidget(self.MainSection)
        self.GroupingOption.setGeometry(QtCore.QRect(250, 405, 271, 121))
        self.GroupingOption.setStyleSheet("#GroupingOption\n"
"{\n"
"    border: 0.5px solid #052659;\n"
"    background-color: #87ceeb;\n"
"    border-radius: 17px;\n"
"}")
        self.GroupingOption.setObjectName("GroupingOption")
        self.GroupByCategory = QtWidgets.QPushButton(self.GroupingOption)
        self.GroupByCategory.setGeometry(QtCore.QRect(10, 60, 251, 41))
        self.GroupByCategory.setStyleSheet("#GroupByCategory{\n"
"    font-family: Rubik;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.GroupByCategory.setObjectName("GroupByCategory")
        self.GroupByStatus = QtWidgets.QPushButton(self.GroupingOption)
        self.GroupByStatus.setGeometry(QtCore.QRect(10, 10, 251, 41))
        self.GroupByStatus.setStyleSheet("#GroupByStatus{\n"
"    font-family: Rubik;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.GroupByStatus.setObjectName("GroupByStatus")
        self.KolomNameTask = QtWidgets.QWidget(self.MainSection)
        self.KolomNameTask.setGeometry(QtCore.QRect(39, 430, 261, 31))
        self.KolomNameTask.setStyleSheet("#KolomNameTask{\n"
"    border : 1px solid #0047ab;\n"
"}")
        self.KolomNameTask.setObjectName("KolomNameTask")
        self.LabelNamaTask = QtWidgets.QLabel(self.KolomNameTask)
        self.LabelNamaTask.setGeometry(QtCore.QRect(80, 5, 81, 20))
        self.LabelNamaTask.setStyleSheet("#LabelNamaTask{\n"
"font-family: \"Roboto\";\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #0E49B5;\n"
"}")
        self.LabelNamaTask.setObjectName("LabelNamaTask")
        self.KolomStatusTask = QtWidgets.QWidget(self.MainSection)
        self.KolomStatusTask.setGeometry(QtCore.QRect(300, 430, 181, 31))
        self.KolomStatusTask.setStyleSheet("#KolomStatusTask{\n"
"    border : 1px solid #0047ab;\n"
"}")
        self.KolomStatusTask.setObjectName("KolomStatusTask")
        self.LabelStatus = QtWidgets.QLabel(self.KolomStatusTask)
        self.LabelStatus.setGeometry(QtCore.QRect(70, 5, 51, 20))
        self.LabelStatus.setStyleSheet("#LabelStatus{\n"
"font-family: \"Roboto\";\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #0E49B5;\n"
"}")
        self.LabelStatus.setObjectName("LabelStatus")
        self.KolomCategory = QtWidgets.QWidget(self.MainSection)
        self.KolomCategory.setGeometry(QtCore.QRect(480, 430, 181, 31))
        self.KolomCategory.setStyleSheet("#KolomCategory{\n"
"    border : 1px solid #0047ab;\n"
"}")
        self.KolomCategory.setObjectName("KolomCategory")
        self.LabelCategory = QtWidgets.QLabel(self.KolomCategory)
        self.LabelCategory.setGeometry(QtCore.QRect(60, 5, 71, 20))
        self.LabelCategory.setStyleSheet("#LabelCategory{\n"
"font-family: \"Roboto\";\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #0E49B5;\n"
"}")
        self.LabelCategory.setObjectName("LabelCategory")
        self.KolomDeadlineTask = QtWidgets.QWidget(self.MainSection)
        self.KolomDeadlineTask.setGeometry(QtCore.QRect(660, 430, 221, 31))
        self.KolomDeadlineTask.setStyleSheet("#KolomDeadlineTask{\n"
"    border : 1px solid #0047ab;\n"
"}")
        self.KolomDeadlineTask.setObjectName("KolomDeadlineTask")
        self.LabelDeadline = QtWidgets.QLabel(self.KolomDeadlineTask)
        self.LabelDeadline.setGeometry(QtCore.QRect(50, 5, 121, 20))
        self.LabelDeadline.setStyleSheet("#LabelDeadline{\n"
"font-family: \"Roboto\";\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #0E49B5;\n"
"}")
        self.LabelDeadline.setObjectName("LabelDeadline")
        self.KolomDescriptionTask = QtWidgets.QWidget(self.MainSection)
        self.KolomDescriptionTask.setGeometry(QtCore.QRect(880, 430, 281, 31))
        self.KolomDescriptionTask.setStyleSheet("#KolomDescriptionTask{\n"
"    border : 1px solid #0047ab;\n"
"}")
        self.KolomDescriptionTask.setObjectName("KolomDescriptionTask")
        self.LabelDescription = QtWidgets.QLabel(self.KolomDescriptionTask)
        self.LabelDescription.setGeometry(QtCore.QRect(90, 5, 91, 20))
        self.LabelDescription.setStyleSheet("#LabelDescription{\n"
"font-family: \"Roboto\";\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #0E49B5;\n"
"}")
        self.LabelDescription.setObjectName("LabelDescription")
        self.AddingNewTask = QtWidgets.QWidget(self.MainSection)
        self.AddingNewTask.setGeometry(QtCore.QRect(625, 365, 281, 451))
        self.AddingNewTask.setStyleSheet("#AddingNewTask{\n"
"    border: 0.5px solid #052659;\n"
"    background-color: #87ceeb;\n"
"    border-radius: 17px;\n"
"}")
        self.AddingNewTask.setObjectName("AddingNewTask")
        self.TaskTitle = QtWidgets.QLabel(self.AddingNewTask)
        self.TaskTitle.setGeometry(QtCore.QRect(20, 20, 101, 21))
        self.TaskTitle.setStyleSheet("#TaskTitle{\n"
"    font-family: Rubik;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.TaskTitle.setObjectName("TaskTitle")
        self.inputTasktitle = QtWidgets.QLineEdit(self.AddingNewTask)
        self.inputTasktitle.setGeometry(QtCore.QRect(10, 50, 251, 31))
        self.inputTasktitle.setStyleSheet("#inputTasktitle{\n"
"    border-radius : 10px;\n"
"    font-family : Roboto;\n"
"     color: #052659;\n"
"}")
        self.inputTasktitle.setObjectName("inputTasktitle")
        self.CreateTask = QtWidgets.QPushButton(self.AddingNewTask)
        self.CreateTask.setGeometry(QtCore.QRect(20, 350, 251, 41))
        self.CreateTask.setStyleSheet("#CreateTask{\n"
"    font-family: Rubik;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.CreateTask.setObjectName("CreateTask")
        self.DeadlineInputTask = QtWidgets.QLabel(self.AddingNewTask)
        self.DeadlineInputTask.setGeometry(QtCore.QRect(20, 100, 101, 21))
        self.DeadlineInputTask.setStyleSheet("#DeadlineInputTask{\n"
"    font-family: Rubik;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.DeadlineInputTask.setObjectName("DeadlineInputTask")
        self.dateEditDeadlineInput = QtWidgets.QDateEdit(self.AddingNewTask)
        self.dateEditDeadlineInput.setGeometry(QtCore.QRect(20, 130, 101, 31))
        self.dateEditDeadlineInput.setStyleSheet("#dateEditDeadlineInput{ \n"
"    font-family : Roboto;\n"
"     color: #052659;\n"
"}")
        self.dateEditDeadlineInput.setObjectName("dateEditDeadlineInput")
        self.CancelCreationTask = QtWidgets.QPushButton(self.AddingNewTask)
        self.CancelCreationTask.setGeometry(QtCore.QRect(20, 400, 251, 41))
        self.CancelCreationTask.setStyleSheet("#CancelCreationTask{\n"
"    font-family: Rubik;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.CancelCreationTask.setObjectName("CancelCreationTask")
        self.DescriptionInputTask = QtWidgets.QLabel(self.AddingNewTask)
        self.DescriptionInputTask.setGeometry(QtCore.QRect(20, 175, 101, 21))
        self.DescriptionInputTask.setStyleSheet("#DescriptionInputTask{\n"
"    font-family: Rubik;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.DescriptionInputTask.setObjectName("DescriptionInputTask")
        self.CategoryInputTask = QtWidgets.QLabel(self.AddingNewTask)
        self.CategoryInputTask.setGeometry(QtCore.QRect(160, 100, 101, 21))
        self.CategoryInputTask.setStyleSheet("#CategoryInputTask{\n"
"    font-family: Rubik;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.CategoryInputTask.setObjectName("CategoryInputTask")
        self.CategoryInputBox = QtWidgets.QComboBox(self.AddingNewTask)
        self.CategoryInputBox.setGeometry(QtCore.QRect(160, 130, 101, 31))
        self.CategoryInputBox.setStyleSheet("#CategoryInputBox{\n"
"    font-family : Roboto;\n"
"     color: #052659; }")
        self.CategoryInputBox.setObjectName("CategoryInputBox")
        self.CategoryInputBox.addItem("")
        self.CategoryInputBox.addItem("")
        self.CategoryInputBox.addItem("")
        self.BoxInputDescription = QtWidgets.QTextEdit(self.AddingNewTask)
        self.BoxInputDescription.setGeometry(QtCore.QRect(10, 200, 261, 131))
        self.BoxInputDescription.setStyleSheet("#BoxInputDescription{\n"
"    border-radius : 10px;\n"
"    font-family : Roboto;\n"
"     color: #052659;\n"
"}")
        self.BoxInputDescription.setObjectName("BoxInputDescription")
        self.SortingOption = QtWidgets.QWidget(self.MainSection)
        self.SortingOption.setGeometry(QtCore.QRect(50, 405, 271, 121))
        self.SortingOption.setStyleSheet("#SortingOption\n"
"{\n"
"    border: 0.5px solid #052659;\n"
"    background-color: #87ceeb;\n"
"    border-radius: 17px;\n"
"}")
        self.SortingOption.setObjectName("SortingOption")
        self.SortDescending = QtWidgets.QPushButton(self.SortingOption)
        self.SortDescending.setGeometry(QtCore.QRect(10, 60, 251, 41))
        self.SortDescending.setStyleSheet("#SortDescending{\n"
"    font-family: Rubik;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Downloads/down (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SortDescending.setIcon(icon)
        self.SortDescending.setObjectName("SortDescending")
        self.SortAscending = QtWidgets.QPushButton(self.SortingOption)
        self.SortAscending.setGeometry(QtCore.QRect(10, 10, 251, 41))
        self.SortAscending.setStyleSheet("#SortAscending{\n"
"    font-family: Rubik;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Downloads/top.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SortAscending.setIcon(icon1)
        self.SortAscending.setObjectName("SortAscending")
        self.ProgressBar = QtWidgets.QLabel(self.MainSection)
        self.ProgressBar.setGeometry(QtCore.QRect(840, 40, 561, 71))
        self.ProgressBar.setStyleSheet("#ProgressBar{\n"
"    font: 45px \"Roboto\";\n"
"    color: #0E49B5;\n"
"    font-weight: bold;\n"
"}")
        self.ProgressBar.setObjectName("ProgressBar")
        self.SemangatTitle = QtWidgets.QLabel(self.MainSection)
        self.SemangatTitle.setGeometry(QtCore.QRect(840, 120, 591, 31))
        self.SemangatTitle.setStyleSheet("#SemangatTitle{\n"
"    font: bold 18px \"Roboto\";\n"
"    color: #0E49B5;\n"
"}")
        self.SemangatTitle.setObjectName("SemangatTitle")
        self.progressBar = QtWidgets.QProgressBar(self.MainSection)
        self.progressBar.setGeometry(QtCore.QRect(840, 170, 681, 41))
        self.progressBar.setStyleSheet("#progressBar{\n"
"    font-family: \"Roboto\";\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #0E49B5;\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.EditTask = QtWidgets.QWidget(self.MainSection)
        self.EditTask.setGeometry(QtCore.QRect(1190, 250, 481, 451))
        self.EditTask.setStyleSheet("#EditTask{\n"
"    border: 0.5px solid #052659;\n"
"    background-color: #87ceeb;\n"
"    border-radius: 17px;\n"
"}")
        self.EditTask.setObjectName("EditTask")
        self.TaskTitleEdit = QtWidgets.QLabel(self.EditTask)
        self.TaskTitleEdit.setGeometry(QtCore.QRect(20, 20, 101, 21))
        self.TaskTitleEdit.setStyleSheet("#TaskTitleEdit{\n"
"    font-family: Rubik;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.TaskTitleEdit.setObjectName("TaskTitleEdit")
        self.InputEditTaskBox = QtWidgets.QLineEdit(self.EditTask)
        self.InputEditTaskBox.setGeometry(QtCore.QRect(10, 50, 381, 31))
        self.InputEditTaskBox.setStyleSheet("#InputEditTaskBox{\n"
"    border-radius : 10px;\n"
"    font-family : Roboto;\n"
"     color: #052659;\n"
"}")
        self.InputEditTaskBox.setObjectName("InputEditTaskBox")
        self.ApplyChangesButton = QtWidgets.QPushButton(self.EditTask)
        self.ApplyChangesButton.setGeometry(QtCore.QRect(20, 350, 441, 41))
        self.ApplyChangesButton.setStyleSheet("#ApplyChangesButton{\n"
"    font-family: Rubik;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.ApplyChangesButton.setObjectName("ApplyChangesButton")
        self.DeadlineEditInput = QtWidgets.QLabel(self.EditTask)
        self.DeadlineEditInput.setGeometry(QtCore.QRect(20, 100, 101, 21))
        self.DeadlineEditInput.setStyleSheet("#DeadlineEditInput{\n"
"    font-family: Rubik;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.DeadlineEditInput.setObjectName("DeadlineEditInput")
        self.DateEditDeadline = QtWidgets.QDateEdit(self.EditTask)
        self.DateEditDeadline.setGeometry(QtCore.QRect(20, 130, 101, 31))
        self.DateEditDeadline.setStyleSheet("#DateEditDeadline{ \n"
"    font-family : Roboto;\n"
"     color: #052659;\n"
"}")
        self.DateEditDeadline.setObjectName("DateEditDeadline")
        self.CancelingEdit = QtWidgets.QPushButton(self.EditTask)
        self.CancelingEdit.setGeometry(QtCore.QRect(20, 400, 441, 41))
        self.CancelingEdit.setStyleSheet("#CancelingEdit{\n"
"    font-family: Rubik;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.CancelingEdit.setObjectName("CancelingEdit")
        self.DescriptionTitle = QtWidgets.QLabel(self.EditTask)
        self.DescriptionTitle.setGeometry(QtCore.QRect(20, 175, 101, 21))
        self.DescriptionTitle.setStyleSheet("#DescriptionTitle{\n"
"    font-family: Rubik;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.DescriptionTitle.setObjectName("DescriptionTitle")
        self.CategoryTitle = QtWidgets.QLabel(self.EditTask)
        self.CategoryTitle.setGeometry(QtCore.QRect(160, 100, 101, 21))
        self.CategoryTitle.setStyleSheet("#CategoryTitle{\n"
"    font-family: Rubik;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.CategoryTitle.setObjectName("CategoryTitle")
        self.CategoryEditComboBox = QtWidgets.QComboBox(self.EditTask)
        self.CategoryEditComboBox.setGeometry(QtCore.QRect(160, 130, 101, 31))
        self.CategoryEditComboBox.setStyleSheet("#CategoryEditComboBox{\n"
"    font-family : Roboto;\n"
"     color: #052659; }")
        self.CategoryEditComboBox.setObjectName("CategoryEditComboBox")
        self.CategoryEditComboBox.addItem("")
        self.CategoryEditComboBox.addItem("")
        self.CategoryEditComboBox.addItem("")
        self.DescriptionEditBox = QtWidgets.QTextEdit(self.EditTask)
        self.DescriptionEditBox.setGeometry(QtCore.QRect(10, 200, 451, 131))
        self.DescriptionEditBox.setStyleSheet("#DescriptionEditBox{\n"
"    border-radius : 10px;\n"
"    font-family : Roboto;\n"
"     color: #052659;\n"
"}")
        self.DescriptionEditBox.setObjectName("DescriptionEditBox")
        self.StatusTitle = QtWidgets.QLabel(self.EditTask)
        self.StatusTitle.setGeometry(QtCore.QRect(290, 100, 101, 21))
        self.StatusTitle.setStyleSheet("#StatusTitle{\n"
"    font-family: Rubik;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"   color: #052659;\n"
"}")
        self.StatusTitle.setObjectName("StatusTitle")
        self.StatusComboBox = QtWidgets.QComboBox(self.EditTask)
        self.StatusComboBox.setGeometry(QtCore.QRect(290, 130, 171, 31))
        self.StatusComboBox.setStyleSheet("#StatusComboBox{\n"
"    font-family : Roboto;\n"
"     color: #052659; }")
        self.StatusComboBox.setObjectName("StatusComboBox")
        self.StatusComboBox.addItem("")
        self.StatusComboBox.addItem("")
        self.StatusComboBox.addItem("")
        self.BackToBoardUpper = QtWidgets.QPushButton(self.MainSection)
        self.BackToBoardUpper.setGeometry(QtCore.QRect(101, 5, 81, 21))
        self.BackToBoardUpper.setStyleSheet("#BackToBoardUpper{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color:  #0E49B5;;\n"
"}")
        self.BackToBoardUpper.setObjectName("BackToBoardUpper")
        self.Containerforwords.raise_()
        self.YourTask.raise_()
        self.AddNewTaskButton.raise_()
        self.TaskNameTitle.raise_()
        self.Sorting.raise_()
        self.BackToDashboardUpper.raise_()
        self.widgetContainerTask.raise_()
        self.CurrentTaskUpper.raise_()
        self.Grouping.raise_()
        self.KolomNameTask.raise_()
        self.KolomStatusTask.raise_()
        self.KolomCategory.raise_()
        self.KolomDeadlineTask.raise_()
        self.KolomDescriptionTask.raise_()
        self.GroupingOption.raise_()
        self.AddingNewTask.raise_()
        self.SortingOption.raise_()
        self.ProgressBar.raise_()
        self.SemangatTitle.raise_()
        self.progressBar.raise_()
        self.EditTask.raise_()
        self.BackToBoardUpper.raise_()
        self.Searchbar = QtWidgets.QWidget(Ergo)
        self.Searchbar.setGeometry(QtCore.QRect(200, 0, 1721, 61))
        self.Searchbar.setStyleSheet("#Searchbar{\n"
"    background: qlineargradient(x1:0, y1:0, x2:2, y2:1, stop:0 #73c2fb, stop:1 #1560bd);\n"
"    border : none;\n"
"}")
        self.Searchbar.setObjectName("Searchbar")
        self.SearchBoard = QtWidgets.QLineEdit(self.Searchbar)
        self.SearchBoard.setGeometry(QtCore.QRect(20, 20, 811, 31))
        self.SearchBoard.setStyleSheet("#SearchBoard{\n"
"    border-radius : 10px;\n"
"    font-family : Rubik;\n"
"    color : #6C6C6C;\n"
"    font-size : 15px;\n"
"}")
        self.SearchBoard.setObjectName("SearchBoard")
        self.SmileyFace = QtWidgets.QLabel(self.Searchbar)
        self.SmileyFace.setGeometry(QtCore.QRect(1530, 10, 41, 41))
        self.SmileyFace.setText("")
        self.SmileyFace.setPixmap(QtGui.QPixmap("../if2250-2024-k03-g04-ergo/img/smileyface.png"))
        self.SmileyFace.setScaledContents(True)
        self.SmileyFace.setObjectName("SmileyFace")
        self.UserErgo = QtWidgets.QLabel(self.Searchbar)
        self.UserErgo.setGeometry(QtCore.QRect(1580, 20, 71, 21))
        self.UserErgo.setStyleSheet("#UserErgo{\n"
"    font-family : Rubik;\n"
"    font-size : 13px;\n"
"}")
        self.UserErgo.setObjectName("UserErgo")
        self.SearchButton = QtWidgets.QPushButton(self.Searchbar)
        self.SearchButton.setGeometry(QtCore.QRect(830, 20, 41, 31))
        self.SearchButton.setStyleSheet("#SearchButton{\n"
"    border : none;\n"
"}")
        self.SearchButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../if2250-2024-k03-g04-ergo/img/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SearchButton.setIcon(icon2)
        self.SearchButton.setObjectName("SearchButton")
        self.Searchbar.raise_()
        self.MainSection.raise_()
        self.Navbar.raise_()

        self.retranslateUi(Ergo)
        QtCore.QMetaObject.connectSlotsByName(Ergo)

    def retranslateUi(self, Ergo):
        _translate = QtCore.QCoreApplication.translate
        Ergo.setWindowTitle(_translate("Ergo", "Ergo"))
        self.BackToDashboard.setText(_translate("Ergo", "Dashboard"))
        self.BackToYourBoard.setText(_translate("Ergo", "Your Board"))
        self.TaskNameTitle.setText(_translate("Ergo", "Build UI"))
        self.Welcome.setText(_translate("Ergo", "Welcome!"))
        self.WelcomingTitle.setText(_translate("Ergo", "This is your work space to track all of your task and project"))
        self.YourTask.setText(_translate("Ergo", "Your Task"))
        self.AddNewTaskButton.setText(_translate("Ergo", "+ Add New Task"))
        self.Sorting.setText(_translate("Ergo", "Sort By"))
        self.BackToDashboardUpper.setText(_translate("Ergo", "Dashboard"))
        self.Task1Name.setText(_translate("Ergo", "Inserting Image"))
        self.Task1Status.setText(_translate("Ergo", "Not Started"))
        self.Task1Category.setText(_translate("Ergo", "High"))
        self.Task1Deadline.setText(_translate("Ergo", "2023-01-01 / 07.00"))
        self.Task1Description.setHtml(_translate("Ergo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:13px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:15px; font-weight:696;\">Memasukkan gambar serta memberikan deskripsi gambar yang tertera </span></p></body></html>"))
        self.Task2Name.setText(_translate("Ergo", "Inserting Image"))
        self.Task2Status.setText(_translate("Ergo", "Not Started"))
        self.Task2Category.setText(_translate("Ergo", "High"))
        self.Task2Deadline.setText(_translate("Ergo", "2023-01-01 / 07.00"))
        self.Task2Description.setHtml(_translate("Ergo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:13px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:15px; font-weight:696;\">Memasukkan gambar serta memberikan deskripsi gambar yang tertera </span></p></body></html>"))
        self.CurrentTaskUpper.setText(_translate("Ergo", "> Build UI"))
        self.Grouping.setText(_translate("Ergo", "Group By"))
        self.GroupByCategory.setText(_translate("Ergo", "Group by Category"))
        self.GroupByStatus.setText(_translate("Ergo", "Group by Status"))
        self.LabelNamaTask.setText(_translate("Ergo", "Task Name"))
        self.LabelStatus.setText(_translate("Ergo", "Status"))
        self.LabelCategory.setText(_translate("Ergo", "Category"))
        self.LabelDeadline.setText(_translate("Ergo", "Due Date / Time"))
        self.LabelDescription.setText(_translate("Ergo", "Description"))
        self.TaskTitle.setText(_translate("Ergo", "Task Title"))
        self.CreateTask.setText(_translate("Ergo", "Create Task"))
        self.DeadlineInputTask.setText(_translate("Ergo", "Deadline"))
        self.CancelCreationTask.setText(_translate("Ergo", "Cancel"))
        self.DescriptionInputTask.setText(_translate("Ergo", "Description"))
        self.CategoryInputTask.setText(_translate("Ergo", "Category"))
        self.CategoryInputBox.setItemText(0, _translate("Ergo", "High"))
        self.CategoryInputBox.setItemText(1, _translate("Ergo", "Medium"))
        self.CategoryInputBox.setItemText(2, _translate("Ergo", "Low"))
        self.SortDescending.setText(_translate("Ergo", "Sort Descending"))
        self.SortAscending.setText(_translate("Ergo", "Sort Ascending"))
        self.ProgressBar.setText(_translate("Ergo", "Progress Bar"))
        self.SemangatTitle.setText(_translate("Ergo", "Keep it up, you\'re almost there :D"))
        self.TaskTitleEdit.setText(_translate("Ergo", "Task Title"))
        self.ApplyChangesButton.setText(_translate("Ergo", "Apply Changes"))
        self.DeadlineEditInput.setText(_translate("Ergo", "Deadline"))
        self.CancelingEdit.setText(_translate("Ergo", "Cancel"))
        self.DescriptionTitle.setText(_translate("Ergo", "Description"))
        self.CategoryTitle.setText(_translate("Ergo", "Category"))
        self.CategoryEditComboBox.setItemText(0, _translate("Ergo", "High"))
        self.CategoryEditComboBox.setItemText(1, _translate("Ergo", "Medium"))
        self.CategoryEditComboBox.setItemText(2, _translate("Ergo", "Low"))
        self.StatusTitle.setText(_translate("Ergo", "Status"))
        self.StatusComboBox.setItemText(0, _translate("Ergo", "Not Yet Started"))
        self.StatusComboBox.setItemText(1, _translate("Ergo", "On Progress"))
        self.StatusComboBox.setItemText(2, _translate("Ergo", "Completed"))
        self.BackToBoardUpper.setText(_translate("Ergo", "> Mobile Development"))
        self.SearchBoard.setText(_translate("Ergo", "          Search Your Board"))
        self.UserErgo.setText(_translate("Ergo", "  User Ergo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ergo = QtWidgets.QWidget()
    ui = Ui_Ergo()
    ui.setupUi(Ergo)
    Ergo.show()
    sys.exit(app.exec_())
